config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :admin do

    resources :roles do
      resources :admin_users
    end

    resources :students do
      resources :observations
      resources :developmental_levels
    end

    resources :students do
      resource :evaluation_detail
    end
    
  end #end namespace

  root to: "admin/dashboard#index"

end

app/models/observation.rb
class Observation < ActiveRecord::Base

belongs_to :student

 validate :student_id, presence: true
 validate :validate_date
  
  def validate_date
    if observed_on.nil? or observed_on > Date.today
      errors.add(:observed_on, "PROBLEM:  Observation date cannot be in the future.")
    end #if
  end #method
end

app/controllers/observations_controller.rb
class ObservationsController < InheritedResources::Base

  private

    def observation_params
      params.require(:observation).permit(:student_id, :date_on, :name, :birthdate, :grade, :teacher, :allergies, :diet, :sleep, :elimination, :concerns, :stability, :parent_histories, :household_members, :community_supports, :interaction_patterns, :well_attuned, :avoidant, :vigilant, :over_stimulating, :sensory_registration, :sensory_orientation, :sensory_interpretation, :response_organization, :response_execution, :adaptability, :sensory_threshold, :sensory_seeking_behaviors, :shares_attention, :regulation, :engagement, :interactions, :individuation, :mood, :solves_problems, :imagination, :creativity, :reasoning, :links_emotions, :perspective, :multiCausal_thinking, :selfReflective_thinking)
    end
end

app/views/observations/_form.html.erb
<%= form_for(@observation) do |f| %>
  <% if @observation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@observation.errors.count, "error") %> prohibited this observation from being saved:</h2>

      <ul>
      <% @observation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.text_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :date_on %><br>
    <%= f.datetime_select :date_on %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :birthdate %><br>
    <%= f.datetime_select :birthdate %>
  </div>
  <div class="field">
    <%= f.label :grade %><br>
    <%= f.text_field :grade %>
  </div>
  <div class="field">
    <%= f.label :teacher %><br>
    <%= f.text_field :teacher %>
  </div>
  <div class="field">
    <%= f.label :allergies %><br>
    <%= f.text_field :allergies %>
  </div>
  <div class="field">
    <%= f.label :diet %><br>
    <%= f.text_field :diet %>
  </div>
  <div class="field">
    <%= f.label :sleep %><br>
    <%= f.text_field :sleep %>
  </div>
  <div class="field">
    <%= f.label :elimination %><br>
    <%= f.text_field :elimination %>
  </div>
  <div class="field">
    <%= f.label :concerns %><br>
    <%= f.text_field :concerns %>
  </div>
  <div class="field">
    <%= f.label :stability %><br>
    <%= f.text_field :stability %>
  </div>
  <div class="field">
    <%= f.label :parent_histories %><br>
    <%= f.text_field :parent_histories %>
  </div>
  <div class="field">
    <%= f.label :household_members %><br>
    <%= f.text_field :household_members %>
  </div>
  <div class="field">
    <%= f.label :community_supports %><br>
    <%= f.text_field :community_supports %>
  </div>
  <div class="field">
    <%= f.label :interaction_patterns %><br>
    <%= f.text_field :interaction_patterns %>
  </div>
  <div class="field">
    <%= f.label :well_attuned %><br>
    <%= f.text_field :well_attuned %>
  </div>
  <div class="field">
    <%= f.label :avoidant %><br>
    <%= f.text_field :avoidant %>
  </div>
  <div class="field">
    <%= f.label :vigilant %><br>
    <%= f.text_field :vigilant %>
  </div>
  <div class="field">
    <%= f.label :over_stimulating %><br>
    <%= f.text_field :over_stimulating %>
  </div>
  <div class="field">
    <%= f.label :sensory_registration %><br>
    <%= f.text_field :sensory_registration %>
  </div>
  <div class="field">
    <%= f.label :sensory_orientation %><br>
    <%= f.text_field :sensory_orientation %>
  </div>
  <div class="field">
    <%= f.label :sensory_interpretation %><br>
    <%= f.text_field :sensory_interpretation %>
  </div>
  <div class="field">
    <%= f.label :response_organization %><br>
    <%= f.text_field :response_organization %>
  </div>
  <div class="field">
    <%= f.label :response_execution %><br>
    <%= f.text_field :response_execution %>
  </div>
  <div class="field">
    <%= f.label :adaptability %><br>
    <%= f.text_field :adaptability %>
  </div>
  <div class="field">
    <%= f.label :sensory_threshold %><br>
    <%= f.text_field :sensory_threshold %>
  </div>
  <div class="field">
    <%= f.label :sensory_seeking_behaviors %><br>
    <%= f.text_field :sensory_seeking_behaviors %>
  </div>
  <div class="field">
    <%= f.label :shares_attention %><br>
    <%= f.text_field :shares_attention %>
  </div>
  <div class="field">
    <%= f.label :regulation %><br>
    <%= f.text_field :regulation %>
  </div>
  <div class="field">
    <%= f.label :engagement %><br>
    <%= f.text_field :engagement %>
  </div>
  <div class="field">
    <%= f.label :interactions %><br>
    <%= f.text_field :interactions %>
  </div>
  <div class="field">
    <%= f.label :individuation %><br>
    <%= f.text_field :individuation %>
  </div>
  <div class="field">
    <%= f.label :mood %><br>
    <%= f.text_field :mood %>
  </div>
  <div class="field">
    <%= f.label :solves_problems %><br>
    <%= f.text_field :solves_problems %>
  </div>
  <div class="field">
    <%= f.label :imagination %><br>
    <%= f.text_field :imagination %>
  </div>
  <div class="field">
    <%= f.label :creativity %><br>
    <%= f.text_field :creativity %>
  </div>
  <div class="field">
    <%= f.label :reasoning %><br>
    <%= f.text_field :reasoning %>
  </div>
  <div class="field">
    <%= f.label :links_emotions %><br>
    <%= f.text_field :links_emotions %>
  </div>
  <div class="field">
    <%= f.label :perspective %><br>
    <%= f.text_field :perspective %>
  </div>
  <div class="field">
    <%= f.label :multiCausal_thinking %><br>
    <%= f.text_field :multiCausal_thinking %>
  </div>
  <div class="field">
    <%= f.label :selfReflective_thinking %><br>
    <%= f.text_field :selfReflective_thinking %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/observations/edit.html.erb
<h1>Editing observation</h1>

<%= render 'form' %>

<%= link_to 'Show', @observation %> |
<%= link_to 'Back', observations_path %>

app/views/observations/index.html.erb
<h1>Listing observations</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Date on</th>
      <th>Name</th>
      <th>Birthdate</th>
      <th>Grade</th>
      <th>Teacher</th>
      <th>Allergies</th>
      <th>Diet</th>
      <th>Sleep</th>
      <th>Elimination</th>
      <th>Concerns</th>
      <th>Stability</th>
      <th>Parent histories</th>
      <th>Household members</th>
      <th>Community supports</th>
      <th>Interaction patterns</th>
      <th>Well attuned</th>
      <th>Avoidant</th>
      <th>Vigilant</th>
      <th>Over stimulating</th>
      <th>Sensory registration</th>
      <th>Sensory orientation</th>
      <th>Sensory interpretation</th>
      <th>Response organization</th>
      <th>Response execution</th>
      <th>Adaptability</th>
      <th>Sensory threshold</th>
      <th>Sensory seeking behaviors</th>
      <th>Shares attention</th>
      <th>Regulation</th>
      <th>Engagement</th>
      <th>Interactions</th>
      <th>Individuation</th>
      <th>Mood</th>
      <th>Solves problems</th>
      <th>Imagination</th>
      <th>Creativity</th>
      <th>Reasoning</th>
      <th>Links emotions</th>
      <th>Perspective</th>
      <th>Multicausal thinking</th>
      <th>Selfreflective thinking</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @observations.each do |observation| %>
      <tr>
        <td><%= observation.student_id %></td>
        <td><%= observation.date_on %></td>
        <td><%= observation.name %></td>
        <td><%= observation.birthdate %></td>
        <td><%= observation.grade %></td>
        <td><%= observation.teacher %></td>
        <td><%= observation.allergies %></td>
        <td><%= observation.diet %></td>
        <td><%= observation.sleep %></td>
        <td><%= observation.elimination %></td>
        <td><%= observation.concerns %></td>
        <td><%= observation.stability %></td>
        <td><%= observation.parent_histories %></td>
        <td><%= observation.household_members %></td>
        <td><%= observation.community_supports %></td>
        <td><%= observation.interaction_patterns %></td>
        <td><%= observation.well_attuned %></td>
        <td><%= observation.avoidant %></td>
        <td><%= observation.vigilant %></td>
        <td><%= observation.over_stimulating %></td>
        <td><%= observation.sensory_registration %></td>
        <td><%= observation.sensory_orientation %></td>
        <td><%= observation.sensory_interpretation %></td>
        <td><%= observation.response_organization %></td>
        <td><%= observation.response_execution %></td>
        <td><%= observation.adaptability %></td>
        <td><%= observation.sensory_threshold %></td>
        <td><%= observation.sensory_seeking_behaviors %></td>
        <td><%= observation.shares_attention %></td>
        <td><%= observation.regulation %></td>
        <td><%= observation.engagement %></td>
        <td><%= observation.interactions %></td>
        <td><%= observation.individuation %></td>
        <td><%= observation.mood %></td>
        <td><%= observation.solves_problems %></td>
        <td><%= observation.imagination %></td>
        <td><%= observation.creativity %></td>
        <td><%= observation.reasoning %></td>
        <td><%= observation.links_emotions %></td>
        <td><%= observation.perspective %></td>
        <td><%= observation.multiCausal_thinking %></td>
        <td><%= observation.selfReflective_thinking %></td>
        <td><%= link_to 'Show', observation %></td>
        <td><%= link_to 'Edit', edit_observation_path(observation) %></td>
        <td><%= link_to 'Destroy', observation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Observation', new_observation_path %>

app/views/observations/new.html.erb
<h1>New observation</h1>

<%= render 'form' %>

<%= link_to 'Back', observations_path %>

app/views/observations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @observation.student_id %>
</p>

<p>
  <strong>Date on:</strong>
  <%= @observation.date_on %>
</p>

<p>
  <strong>Name:</strong>
  <%= @observation.name %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @observation.birthdate %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @observation.grade %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @observation.teacher %>
</p>

<p>
  <strong>Allergies:</strong>
  <%= @observation.allergies %>
</p>

<p>
  <strong>Diet:</strong>
  <%= @observation.diet %>
</p>

<p>
  <strong>Sleep:</strong>
  <%= @observation.sleep %>
</p>

<p>
  <strong>Elimination:</strong>
  <%= @observation.elimination %>
</p>

<p>
  <strong>Concerns:</strong>
  <%= @observation.concerns %>
</p>

<p>
  <strong>Stability:</strong>
  <%= @observation.stability %>
</p>

<p>
  <strong>Parent histories:</strong>
  <%= @observation.parent_histories %>
</p>

<p>
  <strong>Household members:</strong>
  <%= @observation.household_members %>
</p>

<p>
  <strong>Community supports:</strong>
  <%= @observation.community_supports %>
</p>

<p>
  <strong>Interaction patterns:</strong>
  <%= @observation.interaction_patterns %>
</p>

<p>
  <strong>Well attuned:</strong>
  <%= @observation.well_attuned %>
</p>

<p>
  <strong>Avoidant:</strong>
  <%= @observation.avoidant %>
</p>

<p>
  <strong>Vigilant:</strong>
  <%= @observation.vigilant %>
</p>

<p>
  <strong>Over stimulating:</strong>
  <%= @observation.over_stimulating %>
</p>

<p>
  <strong>Sensory registration:</strong>
  <%= @observation.sensory_registration %>
</p>

<p>
  <strong>Sensory orientation:</strong>
  <%= @observation.sensory_orientation %>
</p>

<p>
  <strong>Sensory interpretation:</strong>
  <%= @observation.sensory_interpretation %>
</p>

<p>
  <strong>Response organization:</strong>
  <%= @observation.response_organization %>
</p>

<p>
  <strong>Response execution:</strong>
  <%= @observation.response_execution %>
</p>

<p>
  <strong>Adaptability:</strong>
  <%= @observation.adaptability %>
</p>

<p>
  <strong>Sensory threshold:</strong>
  <%= @observation.sensory_threshold %>
</p>

<p>
  <strong>Sensory seeking behaviors:</strong>
  <%= @observation.sensory_seeking_behaviors %>
</p>

<p>
  <strong>Shares attention:</strong>
  <%= @observation.shares_attention %>
</p>

<p>
  <strong>Regulation:</strong>
  <%= @observation.regulation %>
</p>

<p>
  <strong>Engagement:</strong>
  <%= @observation.engagement %>
</p>

<p>
  <strong>Interactions:</strong>
  <%= @observation.interactions %>
</p>

<p>
  <strong>Individuation:</strong>
  <%= @observation.individuation %>
</p>

<p>
  <strong>Mood:</strong>
  <%= @observation.mood %>
</p>

<p>
  <strong>Solves problems:</strong>
  <%= @observation.solves_problems %>
</p>

<p>
  <strong>Imagination:</strong>
  <%= @observation.imagination %>
</p>

<p>
  <strong>Creativity:</strong>
  <%= @observation.creativity %>
</p>

<p>
  <strong>Reasoning:</strong>
  <%= @observation.reasoning %>
</p>

<p>
  <strong>Links emotions:</strong>
  <%= @observation.links_emotions %>
</p>

<p>
  <strong>Perspective:</strong>
  <%= @observation.perspective %>
</p>

<p>
  <strong>Multicausal thinking:</strong>
  <%= @observation.multiCausal_thinking %>
</p>

<p>
  <strong>Selfreflective thinking:</strong>
  <%= @observation.selfReflective_thinking %>
</p>

<%= link_to 'Edit', edit_observation_path(@observation) %> |
<%= link_to 'Back', observations_path %>