config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :admin do

    resources :roles do
      resources :admin_users
    end

    resources :students do
      resources :observations
      resources :developmental_levels
    end

    resources :students do
      resource :evaluation_detail
    end
    
  end #end namespace

  root to: "admin/dashboard#index"

end

app/models/developmental_level.rb
class DevelopmentalLevel < ActiveRecord::Base

  belongs_to :student

  #
  # V A L I D A T I O N S
  #

  validate :validate_date
  validate :duration, presence: true
  validate :student_id, presence: true
  validate :recorder, presence: true

  # TODO -- Create a way to warn the admin user a date is missing and defaulted.
  def validate_date
    if self.observed_on.nil? 
      errors.add(:observed_on, "NOTE: No observation date given, used today's date.")
      self.observed_on = Date.today
    end
    if self.observed_on < Date.new(2014, 11, 01)
      self.observed_on = Date.today
      errors.add(:observed_on, "PROBLEM: Observation date appears to be wrong, is was set to today's date.")
    end
    if self.observed_on > Date.today
      errors.add(:observed_on, "PROBLEM:  Observation date must be provided and cannot be in the future.")
    end #if
  end #method

end #class

app/controllers/developmental_levels_controller.rb
class DevelopmentalLevelsController < InheritedResources::Base

  def index
  end

  private

    def developmental_level_params
      params.require(:developmental_level).permit(:student_id, :observed_on, :recorder, 
      	:fba_not_present, :fba_fleeting, :fba_constricted, :fba_stable,
      	:ibc_not_present, :ibc_fleeting, :ibc_constricted, :ibc_stable,
      	:sm_not_present, :sm_fleeting, :sm_constricted, :sm_stable, 
      	:p_not_present, :p_fleeting, :p_constricted, :p_stable, 
      	:d_not_present, :d_fleeting, :d_constricted, :d_stable, 
      	:wo_not_present, :wo_fleeting, :wo_constricted, :wo_stable, 
      	:duration)
    end
end

app/views/developmental_levels/_form.html.erb
<%= form_for(@developmental_level) do |f| %>
  <% if @developmental_level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@developmental_level.errors.count, "error") %> prohibited this developmental_level from being saved:</h2>

      <ul>
      <% @developmental_level.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student, %><br>
    <%= f.text_field :student, %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :recorder, %><br>
    <%= f.text_field :recorder, %>
  </div>
  <div class="field">
    <%= f.label :fba_not_present, %><br>
    <%= f.text_field :fba_not_present, %>
  </div>
  <div class="field">
    <%= f.label :fba_fleeting, %><br>
    <%= f.text_field :fba_fleeting, %>
  </div>
  <div class="field">
    <%= f.label :fba_constricted, %><br>
    <%= f.text_field :fba_constricted, %>
  </div>
  <div class="field">
    <%= f.label :fba_stable, %><br>
    <%= f.text_field :fba_stable, %>
  </div>
  <div class="field">
    <%= f.label :ibc_not_present, %><br>
    <%= f.text_field :ibc_not_present, %>
  </div>
  <div class="field">
    <%= f.label :ibc_fleeting, %><br>
    <%= f.text_field :ibc_fleeting, %>
  </div>
  <div class="field">
    <%= f.label :ibc_constricted, %><br>
    <%= f.text_field :ibc_constricted, %>
  </div>
  <div class="field">
    <%= f.label :ibc_stable, %><br>
    <%= f.text_field :ibc_stable, %>
  </div>
  <div class="field">
    <%= f.label :sm_not_present, %><br>
    <%= f.text_field :sm_not_present, %>
  </div>
  <div class="field">
    <%= f.label :sm_fleeting, %><br>
    <%= f.text_field :sm_fleeting, %>
  </div>
  <div class="field">
    <%= f.label :sm_constricted, %><br>
    <%= f.text_field :sm_constricted, %>
  </div>
  <div class="field">
    <%= f.label :sm_stable, %><br>
    <%= f.text_field :sm_stable, %>
  </div>
  <div class="field">
    <%= f.label :p_not_present, %><br>
    <%= f.text_field :p_not_present, %>
  </div>
  <div class="field">
    <%= f.label :p_fleeting, %><br>
    <%= f.text_field :p_fleeting, %>
  </div>
  <div class="field">
    <%= f.label :p_constricted, %><br>
    <%= f.text_field :p_constricted, %>
  </div>
  <div class="field">
    <%= f.label :p_stable, %><br>
    <%= f.text_field :p_stable, %>
  </div>
  <div class="field">
    <%= f.label :d_not_present, %><br>
    <%= f.text_field :d_not_present, %>
  </div>
  <div class="field">
    <%= f.label :d_fleeting, %><br>
    <%= f.text_field :d_fleeting, %>
  </div>
  <div class="field">
    <%= f.label :d_constricted, %><br>
    <%= f.text_field :d_constricted, %>
  </div>
  <div class="field">
    <%= f.label :d_stable, %><br>
    <%= f.text_field :d_stable, %>
  </div>
  <div class="field">
    <%= f.label :wo_not_present, %><br>
    <%= f.text_field :wo_not_present, %>
  </div>
  <div class="field">
    <%= f.label :wo_fleeting, %><br>
    <%= f.text_field :wo_fleeting, %>
  </div>
  <div class="field">
    <%= f.label :wo_constricted, %><br>
    <%= f.text_field :wo_constricted, %>
  </div>
  <div class="field">
    <%= f.label :wo_stable, %><br>
    <%= f.text_field :wo_stable, %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/developmental_levels/edit.html.erb
<h1>Editing developmental_level</h1>

<%= render 'form' %>

<%= link_to 'Show', @developmental_level %> |
<%= link_to 'Back', developmental_levels_path %>

app/views/developmental_levels/index.html.erb
<h1>Listing developmental_levels</h1>

<table>
  <thead>
    <tr>
      <th>Student,</th>
      <th>Date</th>
      <th>Recorder,</th>
      <th>Fba not present,</th>
      <th>Fba fleeting,</th>
      <th>Fba constricted,</th>
      <th>Fba stable,</th>
      <th>Ibc not present,</th>
      <th>Ibc fleeting,</th>
      <th>Ibc constricted,</th>
      <th>Ibc stable,</th>
      <th>Sm not present,</th>
      <th>Sm fleeting,</th>
      <th>Sm constricted,</th>
      <th>Sm stable,</th>
      <th>P not present,</th>
      <th>P fleeting,</th>
      <th>P constricted,</th>
      <th>P stable,</th>
      <th>D not present,</th>
      <th>D fleeting,</th>
      <th>D constricted,</th>
      <th>D stable,</th>
      <th>Wo not present,</th>
      <th>Wo fleeting,</th>
      <th>Wo constricted,</th>
      <th>Wo stable,</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @developmental_levels.each do |developmental_level| %>
      <tr>
        <td><%= developmental_level.student, %></td>
        <td><%= developmental_level.date %></td>
        <td><%= developmental_level.recorder, %></td>
        <td><%= developmental_level.fba_not_present, %></td>
        <td><%= developmental_level.fba_fleeting, %></td>
        <td><%= developmental_level.fba_constricted, %></td>
        <td><%= developmental_level.fba_stable, %></td>
        <td><%= developmental_level.ibc_not_present, %></td>
        <td><%= developmental_level.ibc_fleeting, %></td>
        <td><%= developmental_level.ibc_constricted, %></td>
        <td><%= developmental_level.ibc_stable, %></td>
        <td><%= developmental_level.sm_not_present, %></td>
        <td><%= developmental_level.sm_fleeting, %></td>
        <td><%= developmental_level.sm_constricted, %></td>
        <td><%= developmental_level.sm_stable, %></td>
        <td><%= developmental_level.p_not_present, %></td>
        <td><%= developmental_level.p_fleeting, %></td>
        <td><%= developmental_level.p_constricted, %></td>
        <td><%= developmental_level.p_stable, %></td>
        <td><%= developmental_level.d_not_present, %></td>
        <td><%= developmental_level.d_fleeting, %></td>
        <td><%= developmental_level.d_constricted, %></td>
        <td><%= developmental_level.d_stable, %></td>
        <td><%= developmental_level.wo_not_present, %></td>
        <td><%= developmental_level.wo_fleeting, %></td>
        <td><%= developmental_level.wo_constricted, %></td>
        <td><%= developmental_level.wo_stable, %></td>
        <td><%= developmental_level.time %></td>
        <td><%= link_to 'Show', developmental_level %></td>
        <td><%= link_to 'Edit', edit_developmental_level_path(developmental_level) %></td>
        <td><%= link_to 'Destroy', developmental_level, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Developmental level', new_developmental_level_path %>

app/views/developmental_levels/new.html.erb
<h1>New developmental_level</h1>

<%= render 'form' %>

<%= link_to 'Back', developmental_levels_path %>

app/views/developmental_levels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student,:</strong>
  <%= @developmental_level.student, %>
</p>

<p>
  <strong>Date:</strong>
  <%= @developmental_level.date %>
</p>

<p>
  <strong>Recorder,:</strong>
  <%= @developmental_level.recorder, %>
</p>

<p>
  <strong>Fba not present,:</strong>
  <%= @developmental_level.fba_not_present, %>
</p>

<p>
  <strong>Fba fleeting,:</strong>
  <%= @developmental_level.fba_fleeting, %>
</p>

<p>
  <strong>Fba constricted,:</strong>
  <%= @developmental_level.fba_constricted, %>
</p>

<p>
  <strong>Fba stable,:</strong>
  <%= @developmental_level.fba_stable, %>
</p>

<p>
  <strong>Ibc not present,:</strong>
  <%= @developmental_level.ibc_not_present, %>
</p>

<p>
  <strong>Ibc fleeting,:</strong>
  <%= @developmental_level.ibc_fleeting, %>
</p>

<p>
  <strong>Ibc constricted,:</strong>
  <%= @developmental_level.ibc_constricted, %>
</p>

<p>
  <strong>Ibc stable,:</strong>
  <%= @developmental_level.ibc_stable, %>
</p>

<p>
  <strong>Sm not present,:</strong>
  <%= @developmental_level.sm_not_present, %>
</p>

<p>
  <strong>Sm fleeting,:</strong>
  <%= @developmental_level.sm_fleeting, %>
</p>

<p>
  <strong>Sm constricted,:</strong>
  <%= @developmental_level.sm_constricted, %>
</p>

<p>
  <strong>Sm stable,:</strong>
  <%= @developmental_level.sm_stable, %>
</p>

<p>
  <strong>P not present,:</strong>
  <%= @developmental_level.p_not_present, %>
</p>

<p>
  <strong>P fleeting,:</strong>
  <%= @developmental_level.p_fleeting, %>
</p>

<p>
  <strong>P constricted,:</strong>
  <%= @developmental_level.p_constricted, %>
</p>

<p>
  <strong>P stable,:</strong>
  <%= @developmental_level.p_stable, %>
</p>

<p>
  <strong>D not present,:</strong>
  <%= @developmental_level.d_not_present, %>
</p>

<p>
  <strong>D fleeting,:</strong>
  <%= @developmental_level.d_fleeting, %>
</p>

<p>
  <strong>D constricted,:</strong>
  <%= @developmental_level.d_constricted, %>
</p>

<p>
  <strong>D stable,:</strong>
  <%= @developmental_level.d_stable, %>
</p>

<p>
  <strong>Wo not present,:</strong>
  <%= @developmental_level.wo_not_present, %>
</p>

<p>
  <strong>Wo fleeting,:</strong>
  <%= @developmental_level.wo_fleeting, %>
</p>

<p>
  <strong>Wo constricted,:</strong>
  <%= @developmental_level.wo_constricted, %>
</p>

<p>
  <strong>Wo stable,:</strong>
  <%= @developmental_level.wo_stable, %>
</p>

<p>
  <strong>Time:</strong>
  <%= @developmental_level.time %>
</p>

<%= link_to 'Edit', edit_developmental_level_path(@developmental_level) %> |
<%= link_to 'Back', developmental_levels_path %>