config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :admin do

    resources :roles do
      resources :admin_users
    end

    resources :students do
      resources :observations
      resources :developmental_levels
    end

    resources :students do
      resource :evaluation_detail
    end
    
  end #end namespace

  root to: "admin/dashboard#index"

end

app/models/student.rb
class Student < ActiveRecord::Base

  # :observations are really student profiles and are not usually updated once recorded.
  has_many :observations, 
           :autosave => true, 
           :dependent => :destroy
           
  has_many :developmental_levels,
           :dependent => :destroy

  validates_presence_of :name
  validate :validate_date
  
  def validate_date
    if born_on.nil? or born_on > Date.today
      errors.add(:date_on, "PROBLEM:  Birth date must be past.")
    end #if
  end #method

  #
  # getProgress -- takes string x as one of the progress categories, e.g. 'facilitated_by_adult',
  # retrieves observations on these from DevelopmentalLevels and creates a rudimentary sparkline as
  # aid to visual display of student's progress to date.  Progress_category(s) are :attributes in DevelopmentalLevels.
  # FIXME -- Add protection for invalid values of x; PG::UndefinedColumn ERROR: column "#{x}" does not exist
  # FIXME -- Create as singleton method that loads dls once?
  def getProgress progress_category
    student = Student.find(id)
    dls = student.developmental_levels.select(progress_category).order(observed_on: :asc)
    history = ""
    dls.each do | dl |
      history += dl.send(progress_category.to_sym).to_s + '-'
    end
    history
  end


  # Return detailed evaluation for student instance
  def evaluation_detail
    name
  end

  
  def evaluations
    '1 2'
  end

end #class

app/controllers/students_controller.rb
class StudentsController < InheritedResources::Base

  def index
  end

  private

    def student_params
      params.require(:student).permit(:name, :birthdate, :grade, :teacher, :allergies, :diet, 
      	:sleep, :elimination, :concerns, :stability, :parent_histories, :household_members, 
      	:community_supports, :interaction_patterns, :well_attuned, :avoidant, :vigilant, 
      	:over_stimulating, :sensory_registration, :sensory_orientation, :sensory_interpretation, 
      	:response_organization, :response_execution, :adaptability, :sensory_threshold, 
      	:sensory_seeking_behaviors, :shares_attention, :regulation, :engagement, :interactions, 
      	:individuation, :mood, :solves_problems, :imagination, :creativity, :reasoning, 
      	:links_emotions, :perspective, :multiCausal_thinking, :selfReflective_thinking)
    end
end

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :birthdate %><br>
    <%= f.datetime_select :birthdate %>
  </div>
  <div class="field">
    <%= f.label :grade %><br>
    <%= f.text_field :grade %>
  </div>
  <div class="field">
    <%= f.label :teacher %><br>
    <%= f.text_field :teacher %>
  </div>
  <div class="field">
    <%= f.label :allergies %><br>
    <%= f.text_field :allergies %>
  </div>
  <div class="field">
    <%= f.label :diet %><br>
    <%= f.text_field :diet %>
  </div>
  <div class="field">
    <%= f.label :sleep %><br>
    <%= f.text_field :sleep %>
  </div>
  <div class="field">
    <%= f.label :elimination %><br>
    <%= f.text_field :elimination %>
  </div>
  <div class="field">
    <%= f.label :concerns %><br>
    <%= f.text_field :concerns %>
  </div>
  <div class="field">
    <%= f.label :stability %><br>
    <%= f.text_field :stability %>
  </div>
  <div class="field">
    <%= f.label :parent_histories %><br>
    <%= f.text_field :parent_histories %>
  </div>
  <div class="field">
    <%= f.label :household_members %><br>
    <%= f.text_field :household_members %>
  </div>
  <div class="field">
    <%= f.label :community_supports %><br>
    <%= f.text_field :community_supports %>
  </div>
  <div class="field">
    <%= f.label :interaction_patterns %><br>
    <%= f.text_field :interaction_patterns %>
  </div>
  <div class="field">
    <%= f.label :well_attuned %><br>
    <%= f.check_box :well_attuned %>
  </div>
  <div class="field">
    <%= f.label :avoidant %><br>
    <%= f.check_box :avoidant %>
  </div>
  <div class="field">
    <%= f.label :vigilant %><br>
    <%= f.check_box :vigilant %>
  </div>
  <div class="field">
    <%= f.label :over_stimulating %><br>
    <%= f.check_box :over_stimulating %>
  </div>
  <div class="field">
    <%= f.label :sensory_registration %><br>
    <%= f.text_field :sensory_registration %>
  </div>
  <div class="field">
    <%= f.label :sensory_orientation %><br>
    <%= f.text_field :sensory_orientation %>
  </div>
  <div class="field">
    <%= f.label :sensory_interpretation %><br>
    <%= f.text_field :sensory_interpretation %>
  </div>
  <div class="field">
    <%= f.label :response_organization %><br>
    <%= f.text_field :response_organization %>
  </div>
  <div class="field">
    <%= f.label :response_execution %><br>
    <%= f.text_field :response_execution %>
  </div>
  <div class="field">
    <%= f.label :adaptability %><br>
    <%= f.text_field :adaptability %>
  </div>
  <div class="field">
    <%= f.label :sensory_threshold %><br>
    <%= f.text_field :sensory_threshold %>
  </div>
  <div class="field">
    <%= f.label :sensory_seeking_behaviors %><br>
    <%= f.text_field :sensory_seeking_behaviors %>
  </div>
  <div class="field">
    <%= f.label :shares_attention %><br>
    <%= f.check_box :shares_attention %>
  </div>
  <div class="field">
    <%= f.label :regulation %><br>
    <%= f.text_field :regulation %>
  </div>
  <div class="field">
    <%= f.label :engagement %><br>
    <%= f.text_field :engagement %>
  </div>
  <div class="field">
    <%= f.label :interactions %><br>
    <%= f.text_field :interactions %>
  </div>
  <div class="field">
    <%= f.label :individuation %><br>
    <%= f.text_field :individuation %>
  </div>
  <div class="field">
    <%= f.label :mood %><br>
    <%= f.text_field :mood %>
  </div>
  <div class="field">
    <%= f.label :solves_problems %><br>
    <%= f.check_box :solves_problems %>
  </div>
  <div class="field">
    <%= f.label :imagination %><br>
    <%= f.text_field :imagination %>
  </div>
  <div class="field">
    <%= f.label :creativity %><br>
    <%= f.text_field :creativity %>
  </div>
  <div class="field">
    <%= f.label :reasoning %><br>
    <%= f.text_field :reasoning %>
  </div>
  <div class="field">
    <%= f.label :links_emotions %><br>
    <%= f.text_field :links_emotions %>
  </div>
  <div class="field">
    <%= f.label :perspective %><br>
    <%= f.text_field :perspective %>
  </div>
  <div class="field">
    <%= f.label :multiCausal_thinking %><br>
    <%= f.check_box :multiCausal_thinking %>
  </div>
  <div class="field">
    <%= f.label :selfReflective_thinking %><br>
    <%= f.text_field :selfReflective_thinking %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/_index.html.erb
<p> 
  _index

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Birthdate</th>
      <th>Grade</th>
      <th>Teacher</th>
      <th>Allergies</th>
      <th>Diet</th>
      <th>Sleep</th>
      <th>Elimination</th>
      <th>Concerns</th>
      <th>Stability</th>
      <th>Parent histories</th>
      <th>Household members</th>
      <th>Community supports</th>
      <th>Interaction patterns</th>
      <th>Well attuned</th>
      <th>Avoidant</th>
      <th>Vigilant</th>
      <th>Over stimulating</th>
      <th>Sensory registration</th>
      <th>Sensory orientation</th>
      <th>Sensory interpretation</th>
      <th>Response organization</th>
      <th>Response execution</th>
      <th>Adaptability</th>
      <th>Sensory threshold</th>
      <th>Sensory seeking behaviors</th>
      <th>Shares attention</th>
      <th>Regulation</th>
      <th>Engagement</th>
      <th>Interactions</th>
      <th>Individuation</th>
      <th>Mood</th>
      <th>Solves problems</th>
      <th>Imagination</th>
      <th>Creativity</th>
      <th>Reasoning</th>
      <th>Links emotions</th>
      <th>Perspective</th>
      <th>Multicausal thinking</th>
      <th>Selfreflective thinking</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.birthdate %></td>
        <td><%= student.grade %></td>
        <td><%= student.teacher %></td>
        <td><%= student.allergies %></td>
        <td><%= student.diet %></td>
        <td><%= student.sleep %></td>
        <td><%= student.elimination %></td>
        <td><%= student.concerns %></td>
        <td><%= student.stability %></td>
        <td><%= student.parent_histories %></td>
        <td><%= student.household_members %></td>
        <td><%= student.community_supports %></td>
        <td><%= student.interaction_patterns %></td>
        <td><%= student.well_attuned %></td>
        <td><%= student.avoidant %></td>
        <td><%= student.vigilant %></td>
        <td><%= student.over_stimulating %></td>
        <td><%= student.sensory_registration %></td>
        <td><%= student.sensory_orientation %></td>
        <td><%= student.sensory_interpretation %></td>
        <td><%= student.response_organization %></td>
        <td><%= student.response_execution %></td>
        <td><%= student.adaptability %></td>
        <td><%= student.sensory_threshold %></td>
        <td><%= student.sensory_seeking_behaviors %></td>
        <td><%= student.shares_attention %></td>
        <td><%= student.regulation %></td>
        <td><%= student.engagement %></td>
        <td><%= student.interactions %></td>
        <td><%= student.individuation %></td>
        <td><%= student.mood %></td>
        <td><%= student.solves_problems %></td>
        <td><%= student.imagination %></td>
        <td><%= student.creativity %></td>
        <td><%= student.reasoning %></td>
        <td><%= student.links_emotions %></td>
        <td><%= student.perspective %></td>
        <td><%= student.multiCausal_thinking %></td>
        <td><%= student.selfReflective_thinking %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @student.birthdate %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @student.grade %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @student.teacher %>
</p>

<p>
  <strong>Allergies:</strong>
  <%= @student.allergies %>
</p>

<p>
  <strong>Diet:</strong>
  <%= @student.diet %>
</p>

<p>
  <strong>Sleep:</strong>
  <%= @student.sleep %>
</p>

<p>
  <strong>Elimination:</strong>
  <%= @student.elimination %>
</p>

<p>
  <strong>Concerns:</strong>
  <%= @student.concerns %>
</p>

<p>
  <strong>Stability:</strong>
  <%= @student.stability %>
</p>

<p>
  <strong>Parent histories:</strong>
  <%= @student.parent_histories %>
</p>

<p>
  <strong>Household members:</strong>
  <%= @student.household_members %>
</p>

<p>
  <strong>Community supports:</strong>
  <%= @student.community_supports %>
</p>

<p>
  <strong>Interaction patterns:</strong>
  <%= @student.interaction_patterns %>
</p>

<p>
  <strong>Well attuned:</strong>
  <%= @student.well_attuned %>
</p>

<p>
  <strong>Avoidant:</strong>
  <%= @student.avoidant %>
</p>

<p>
  <strong>Vigilant:</strong>
  <%= @student.vigilant %>
</p>

<p>
  <strong>Over stimulating:</strong>
  <%= @student.over_stimulating %>
</p>

<p>
  <strong>Sensory registration:</strong>
  <%= @student.sensory_registration %>
</p>

<p>
  <strong>Sensory orientation:</strong>
  <%= @student.sensory_orientation %>
</p>

<p>
  <strong>Sensory interpretation:</strong>
  <%= @student.sensory_interpretation %>
</p>

<p>
  <strong>Response organization:</strong>
  <%= @student.response_organization %>
</p>

<p>
  <strong>Response execution:</strong>
  <%= @student.response_execution %>
</p>

<p>
  <strong>Adaptability:</strong>
  <%= @student.adaptability %>
</p>

<p>
  <strong>Sensory threshold:</strong>
  <%= @student.sensory_threshold %>
</p>

<p>
  <strong>Sensory seeking behaviors:</strong>
  <%= @student.sensory_seeking_behaviors %>
</p>

<p>
  <strong>Shares attention:</strong>
  <%= @student.shares_attention %>
</p>

<p>
  <strong>Regulation:</strong>
  <%= @student.regulation %>
</p>

<p>
  <strong>Engagement:</strong>
  <%= @student.engagement %>
</p>

<p>
  <strong>Interactions:</strong>
  <%= @student.interactions %>
</p>

<p>
  <strong>Individuation:</strong>
  <%= @student.individuation %>
</p>

<p>
  <strong>Mood:</strong>
  <%= @student.mood %>
</p>

<p>
  <strong>Solves problems:</strong>
  <%= @student.solves_problems %>
</p>

<p>
  <strong>Imagination:</strong>
  <%= @student.imagination %>
</p>

<p>
  <strong>Creativity:</strong>
  <%= @student.creativity %>
</p>

<p>
  <strong>Reasoning:</strong>
  <%= @student.reasoning %>
</p>

<p>
  <strong>Links emotions:</strong>
  <%= @student.links_emotions %>
</p>

<p>
  <strong>Perspective:</strong>
  <%= @student.perspective %>
</p>

<p>
  <strong>Multicausal thinking:</strong>
  <%= @student.multiCausal_thinking %>
</p>

<p>
  <strong>Selfreflective thinking:</strong>
  <%= @student.selfReflective_thinking %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>